//상수값

// 환경관련
const GRAVITY = 1800;
const FRICTION = 6; // 5~30
const GAME_DURATION = 60000; // ms

// ---- 플레이어 관련 ----
const DEFAULT_PLAYER_HEALTH = 50;
const DEFAULT_PLAYER_SPEED = 300;
const DEFAULT_PLAYER_ACCEL = 2500;

// 점프
const DEFAULT_JUMP_STRENGTH = -600;
const DEFAULT_EXTRA_JUMP = 1;

// not property
const COYOTE_TIME_DURATION = 0.07; // 0.166 * 4프레임
const JUMP_BUFFER_DURATION = 0.05; // 0.166 * 3프레임
const JUMP_CUT_MULTIPLIER = 1.5;


const DEFAULT_MAX_AMMO = 6;
const DEFAULT_SHOOT_RATE = 250; // ms
const DEFAULT_RELOAD_DELAY = 800; // ms : 총을 발사하고 자동 장전 하기까지의 시간
const DEFAULT_RELOAD_RATE = 400; // ms
const DEFAUAT_DAMAGE = 10;

const DEFAULT_RESPAWN_DELAY = 1500; // ms
const DEFAULT_INVINC_DURATION = 2000; //ms


//총알관련
const BULLET_SPEED = 1000;
const BULLET_SIZE = 5;
const BULLET_KNOCKBACK_POWER = {x:400, y:-150};

export {
    GRAVITY, FRICTION, GAME_DURATION,
    DEFAULT_PLAYER_HEALTH, DEFAULT_PLAYER_SPEED, DEFAULT_PLAYER_ACCEL, 
    DEFAULT_JUMP_STRENGTH, DEFAULT_EXTRA_JUMP, COYOTE_TIME_DURATION, JUMP_BUFFER_DURATION, JUMP_CUT_MULTIPLIER,
    DEFAULT_MAX_AMMO, DEFAULT_SHOOT_RATE, DEFAULT_RELOAD_RATE, DEFAULT_RELOAD_DELAY, DEFAUAT_DAMAGE,
    DEFAULT_RESPAWN_DELAY, DEFAULT_INVINC_DURATION,
    BULLET_SPEED, BULLET_SIZE, BULLET_KNOCKBACK_POWER
}
