//상수값

// 환경관련
const GRAVITY = 1800;
const FRICTION = 6; // 5~30
const ROUND_DURATION = 60000; // ms

// ---- 플레이어 관련 ----
const DEFAULT_PLAYER_HEALTH = 50;
const DEFAULT_PLAYER_SPEED = 270;
const DEFAULT_PLAYER_ACCEL = 2500;

// 점프
const DEFAULT_JUMP_STRENGTH = -600;
const DEFAULT_EXTRA_JUMP = 1;

// optimizing constants
const COYOTE_TIME_DURATION = 0.07; // 0.166 * 4프레임
const JUMP_BUFFER_DURATION = 0.05; // 0.166 * 3프레임
const JUMP_CUT_MULTIPLIER = 2;
const JUMP_FLOAT_MULTIPLIER = 0.5;


const DEFAULT_RESPAWN_DELAY = 1500; // ms
const DEFAULT_INVINC_DURATION = 2000; //ms


export {
    GRAVITY, FRICTION, ROUND_DURATION,
    DEFAULT_PLAYER_HEALTH, DEFAULT_PLAYER_SPEED, DEFAULT_PLAYER_ACCEL, 
    DEFAULT_JUMP_STRENGTH, DEFAULT_EXTRA_JUMP, COYOTE_TIME_DURATION, JUMP_BUFFER_DURATION, JUMP_CUT_MULTIPLIER, JUMP_FLOAT_MULTIPLIER,
    DEFAULT_RESPAWN_DELAY, DEFAULT_INVINC_DURATION
}
