//상수값

// 환경관련
const GRAVITY = 1800;
const FRICTION = 9; // 5~30
const GAME_DURATION = 60000; // ms

//플레이어 관련
const DEFAULT_PLAYER_HEALTH = 30;
const DEFAULT_PLAYER_SPEED = 400;
const DEFAULT_PLAYER_ACCEL = 3000;

const DEFAULT_JUMP_STRENGTH = -600;
const DEFAULT_EXTRA_JUMP = 1;

const DEFAULT_MAX_AMMO = 6;
const DEFAULT_SHOOT_RATE = 300; // ms
const DEFAULT_RELOAD_DELAY = 1000; // ms
const DEFAULT_RELOAD_RATE = 600; // ms
const DEFAUAT_DAMAGE = 10;

const DEFAULT_RESPAWN_DELAY = 2000; // ms
const DEFAULT_INVINC_DURATION = 3000; //ms


//총알관련
const BULLET_SPEED = 800;
const BULLET_SIZE = 5;
const BULLET_KNOCKBACK_POWER = 300;

export {
    GRAVITY, FRICTION, GAME_DURATION,
    DEFAULT_PLAYER_HEALTH, DEFAULT_PLAYER_SPEED, DEFAULT_PLAYER_ACCEL, 
    DEFAULT_JUMP_STRENGTH, DEFAULT_EXTRA_JUMP,
    DEFAULT_MAX_AMMO, DEFAULT_SHOOT_RATE, DEFAULT_RELOAD_RATE, DEFAULT_RELOAD_DELAY, DEFAUAT_DAMAGE,
    DEFAULT_RESPAWN_DELAY, DEFAULT_INVINC_DURATION,
    BULLET_SPEED, BULLET_SIZE, BULLET_KNOCKBACK_POWER
}
