import {
    DEFAULT_PLAYER_HEALTH,
    DEFAULT_PLAYER_SPEED,
    DEFAULT_PLAYER_ACCEL,
    DEFAULT_JUMP_STRENGTH,
    DEFAULT_EXTRA_JUMP,
    DEFAULT_MAX_AMMO,
    DEFAULT_RELOAD_DELAY,
    DEFAULT_RELOAD_RATE,
    DEFAULT_SHOOT_RATE
} from './constants.js';

export const Player1Config = {
    id: 1,
    health: DEFAULT_PLAYER_HEALTH,
    x: 50,
    y: 500,
    vx: 0,
    vy: 0,
    speed: DEFAULT_PLAYER_SPEED,
    accel: DEFAULT_PLAYER_ACCEL,
    jumpStrength: DEFAULT_JUMP_STRENGTH,
    width: 30,
    height: 50,
    facing: 1,
    color: 'red',
    shootRate: DEFAULT_SHOOT_RATE,
    bullets: [],
    lastShotTime: 0,
    maxAmmo: DEFAULT_MAX_AMMO,
    currentAmmo: DEFAULT_MAX_AMMO,
    reloading: false,
    reloadTime: 0,
    reloadDelay: DEFAULT_RELOAD_DELAY,
    reloadRate: DEFAULT_RELOAD_RATE,
    extraJump: DEFAULT_EXTRA_JUMP,
    jumpsLeft: DEFAULT_EXTRA_JUMP,
    onGround: true,
    isAlive: true,
    controls: {
        left: 'a',
        right: 'd',
        jump: 'w',
        down: 's',
        shoot: ' '
    }
};

export const Player2Config = {
    id: 2,
    health: DEFAULT_PLAYER_HEALTH,
    x: 720,
    y: 500,
    vx: 0,
    vy: 0,
    speed: DEFAULT_PLAYER_SPEED,
    accel: DEFAULT_PLAYER_ACCEL,
    jumpStrength: DEFAULT_JUMP_STRENGTH,
    width: 30,
    height: 50,
    facing: -1,
    color: 'blue',
    shootRate: DEFAULT_SHOOT_RATE,
    bullets: [],
    lastShotTime: 0,
    maxAmmo: DEFAULT_MAX_AMMO,
    currentAmmo: DEFAULT_MAX_AMMO,
    reloading: false,
    reloadTime: 0,
    reloadDelay: DEFAULT_RELOAD_DELAY,
    reloadRate: DEFAULT_RELOAD_RATE,
    extraJump: DEFAULT_EXTRA_JUMP,
    jumpsLeft: DEFAULT_EXTRA_JUMP,
    onGround: true,
    isAlive: true,
    controls: {
        left: 'ArrowLeft',
        right: 'ArrowRight',
        jump: 'ArrowUp',
        down: 'ArrowDown',
        shoot: '0'
    }
};
